---
title: "spectral"
author: "Vladislav Fedorov"
date: "2025-12-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Analysis C Report

# Abstract 

# Methodologies and Reasons

# Findings 

# Conclusion



## R Markdown

```{r}
library(tidyverse)
library(astsa)
```

```{r}
data <-read_delim("SN_y_tot_V2.0.csv", 
    delim = ";", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, show_col_types = FALSE)
names(data) = c("Year", "Mean Sunspots", "Mean SD", "Observations", "Marker")
data
```

```{r}
data_ts <- data|>
  select(c(2))
data_ts <- ts(data_ts, start = 1700.5)
```

```{r}
tsplot(data_ts)
```

```{r}
x <- data_ts - mean(data_ts)
s_un <- spec.pgram(x, log = "no")
```

```{r}
s_sm <- spec.pgram(x, spans = c(5,5), log = "no", 
                   main="Smoothed Spectral Density")
```

```{r}
spec <- spec.pgram(x, plot=FALSE)
freq_max <- spec$freq[which.max(spec$spec)]
period_est <- 1 / freq_max
period_est
```

```{r}
ar_fit <- ar(x, method = "yw")  
ar_fit$order
s_ar <- spec.ar(x, main="AR Spectral Density Estimate")
```
